/**
 * Minimal YieldVault ABI — only the read-path functions the web app needs.
 * Full ABI is in contracts/out/YieldVault.sol/YieldVault.json (generated by forge build).
 */

export const ERC20_APPROVE_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount",  type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

// IStrategyAdapter read subset — used to value each allocation bucket live.
export const ADAPTER_ABI = [
  {
    name: "totalAssets",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;

// Guardrails.config() — the live on-chain guardrail parameters.
export const GUARDRAILS_ABI = [
  {
    name: "config",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "maxWeightBps", type: "uint16[4]" },
          { name: "minIdleBps", type: "uint16" },
          { name: "minInstantLiquidityBps", type: "uint16" },
          { name: "maxUsdyNotionalUsdc", type: "uint256" },
          { name: "maxSlippageBps", type: "uint16" },
          { name: "maxRebalanceMoveBps", type: "uint16" },
          { name: "minRebalanceInterval", type: "uint32" },
          { name: "tvlCap", type: "uint256" },
          { name: "perTxDepositCap", type: "uint256" },
          { name: "addStrategyTimelock", type: "uint32" },
          { name: "pegWarnBps", type: "uint16" },
          { name: "pegBlockBps", type: "uint16" },
          { name: "pegDeRiskBps", type: "uint16" },
          { name: "oracleMaxAge", type: "uint32" },
          { name: "oracleRangeEndBuffer", type: "uint32" },
        ],
      },
    ],
  },
] as const;

export const BENCHMARK_ABI = [
  {
    name: "decisionCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "outcomeOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "decisionId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "realizedYieldBps",   type: "int256"  },
          { name: "drawdownAvoidedUsdc", type: "uint256" },
          { name: "passiveDeltaBps",     type: "int256"  },
          { name: "measuredAt",          type: "uint64"  },
        ],
      },
    ],
  },
] as const;

export const VAULT_ABI = [
  {
    name: "asset",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    // Vault share token decimals. NOTE: with the ERC-4626 `_decimalsOffset()` of 6
    // (inflation-grief defense, contract I1) this is 12 (asset 6 + offset 6), NOT 6.
    // Read it on-chain rather than hardcoding so share<->raw conversions stay correct.
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    name: "benchmark",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "totalAssets",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "convertToAssets",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "convertToShares",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "assets", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "isKilled",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "decisionCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "deposit",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "receiver", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "redeem",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "receiver", type: "address" },
      { name: "owner", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    // AccessControl role check — used to gate the allocator rebalance panel.
    name: "hasRole",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    // Last rebalance timestamp — for the 1-hour interval guardrail (display + gating).
    name: "lastRebalanceAt",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    // ALLOCATOR-only manual rebalance (Allocator page). Idle/Aave moves carry empty
    // swapData; USDY (slot 2) / AUSD (slot 3) legs carry 1delta calldata the UI fetches
    // from the agent's /swap/quote (the 1delta key stays server-side). The calldata is
    // inert until it runs here, where the adapter's pinned-router + balance-delta minOut
    // bind on-chain — so the swap-routing boundary still holds.
    name: "rebalance",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "targetWeightsBps", type: "uint16[4]" },
      { name: "swapData", type: "bytes[]" },
      { name: "decisionURI", type: "string" },
      { name: "rationaleHash", type: "bytes32" },
      { name: "usdyDexSpotUsdc", type: "uint256" },
    ],
    outputs: [{ name: "decisionId", type: "uint256" }],
  },
  {
    name: "DecisionRecorded",
    type: "event",
    inputs: [
      { name: "id", type: "uint256", indexed: true },
      { name: "kind", type: "uint8", indexed: false },
      { name: "rationaleHash", type: "bytes32", indexed: false },
      { name: "decisionURI", type: "string", indexed: false },
    ],
  },
  // Custom errors the rebalance path can revert with. Declared here so viem can
  // DECODE a revert instead of printing the raw 4-byte selector. The guardrail
  // rejection wraps the failing check's own selector in `reason` — map it to a
  // human-readable string with `describeGuardrailReason` (allocatorRebalance.ts).
  { name: "GuardrailsRejected", type: "error", inputs: [{ name: "reason", type: "bytes4" }] },
  { name: "Killed", type: "error", inputs: [] },
  { name: "GuardrailsNotSet", type: "error", inputs: [] },
  { name: "InsufficientLiquidity", type: "error", inputs: [] },
  { name: "InvalidBucket", type: "error", inputs: [] },
  { name: "RwaAdapterNotSet", type: "error", inputs: [] },
] as const;
